### ISSUE TITLE
Matrix的__mul__好像有问题

### ISSUE THREAD

**Issue by cloudygoose** [Determinant/nerv#23]
这里的c用create方法就是跟self同样大小了，这在矩阵乘法中明显不对吧
是不是加个createBySize()方法？

function nerv.CuMatrix:__mul__(b)
    c = self:create()
    c:mul(self, b, 1.0, 0.0, 'N', 'N')
    return c
end

**Comment by Determinant** [comment]
You're right. I haven't used this function and haven't found this issue.

We could use `nerv.get_type(self.__typename)` to grab the underlying type and construct properly.
